[project]
name = "100-days-of-python-bootcamp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pip>=25.3",
    "ruff>=0.14.10",
]
[tool.ruff]
line-length = 120
